name: dart_console_game
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  path: ^1.8.0
  uuid: ^3.0.7
  collection: 1.17.0
  characters: ^1.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
